### ISSUE TITLE
Ambiguous rule with latest snakemake

### ISSUE THREAD

**Issue by vineetbansal** [vineetbansal/dsprint-pipeline#2]
With snakemake version 5.27.4, we're getting the following error on running the step for downloading data:

```
snakemake --cores 1 --use-conda --until download_exac download_exac_coverage download_hg19_2bit download_uniprot_fasta download_uniprot_idmapping download_phastCons download_phyloP download_pertinint_mafs install_pertinint install_hmmer2 install_hmmer3 install_tabix install_twoBitToFa --dryrun

```

```
AmbiguousRuleException:
Rules pertinint_compute_jsd and pertinint_verify_exons are ambiguous for the file /scratch/gpfs/vineetb/dsprint2/pertinint/ensembl/Homo_sapiens.GRCh37/exons/1.jsd.txt.
Consider starting rule output with a unique prefix, constrain your wildcards, or use the ruleorder directive.
Wildcards:
        pertinint_compute_jsd: chromosome=1
        pertinint_verify_exons: chromosome=1.jsd.txt
Expected input files:
        pertinint_compute_jsd: pertinint-internal/config.py /scratch/gpfs/vineetb/dsprint2/pertinint/ensembl/Homo_sapiens.GRCh37/exons/1 /scratch/gpfs/vineetb/dsprint2/pertinint/ucscgb/hg19alignment/mafs/chr1.maf.gz
        pertinint_verify_exons: pertinint-internal/config.py /scratch/gpfs/vineetb/dsprint2/pertinint/ensembl/Homo_sapiens.GRCh37/Homo_sapiens.GRCh37.pep.all.withgenelocs.fa.gz /scratch/gpfs/vineetb/dsprint2/pertinint/ensembl/Homo_sapiens.GRCh37/dna_smExpected output files:
        pertinint_compute_jsd: /scratch/gpfs/vineetb/dsprint2/pertinint/ensembl/Homo_sapiens.GRCh37/exons/1.jsd.txt
        pertinint_verify_exons: /scratch/gpfs/vineetb/dsprint2/pertinint/ensembl/Homo_sapiens.GRCh37/exons/1.jsd.txt
```

Till this is resolved, snakemake will be pinned to version 5.19.2 in `requirements.txt`
